### ISSUE TITLE
For Tutorial, are we missing passing in AWS-managed provisioning role?

### ISSUE THREAD

**Issue by Analect** [awslabs/aws-proton-plugins-for-backstage#218] opened 2023-04-14 13:54 UTC
@niallthomson or @clareliguori ... thanks for your work on this plugin.

I followed the tutorial, including setting up a `analect-gitops-aws-proton-user` with the appropriate aws-proton policies, as mentioned in [this](https://github.com/awslabs/aws-proton-plugins-for-backstage/issues/217) issue.  For now, I have added the same policies to my `gitops` user, in order to be able to work through the tutorial fully.

As part of the aws-proton setup wizard, you are asked to set up a provisioning pipeline role (see below).

![aws_proton_prereq2_provisioning-pipeline-role](https://user-images.githubusercontent.com/4063815/232057340-5a81c376-ab6e-46ea-b244-d8f20f994665.png)

It seems this is required to setup a proton environment (using the UI approach, at least).

![image](https://user-images.githubusercontent.com/4063815/232055006-189aee6d-e0b5-469d-9b29-9d640968f3a0.png)

Since I think the tutorial template is seeking to do this programmatically, then we are somehow not passing that arn-role for the pipeline-role into the `docs/tutorial-assets/fargate-nginx-template/template.yaml` file somewhere?

Perhaps this is related to why I am getting an error with missing permissioning for `createServiceLinkedRole`.

![image](https://user-images.githubusercontent.com/4063815/232056629-cb28f8a5-dfb5-41aa-87a3-76913619b3eb.png)

To address that temporarily, I added a new policy, although I'm not sure if that is superfluous if there is some fix to what I mention above.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "arn:aws:iam::*:role/aws-service-role/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeAccountAttributes"
            ],
            "Resource": "*"
        }
    ]
}
```

On re-running the task, I then get blocked by the absence of the `fargate-env` ... whose creation I presume should be automated by this task ... but somehow it doesn't know about the pipeline-role.  If you can offer any guidance for me to get this resolved. Thanks.

![image](https://user-images.githubusercontent.com/4063815/232061542-21585246-c8e6-41bb-ba12-0e2112d8272e.png)

By the way, this was the `ProtonRolePolicy-analect-io-aws-proton-pipeline-role`, as generated by the Wizard.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cloudformation:CancelUpdateStack",
                "cloudformation:ContinueUpdateRollback",
                "cloudformation:CreateChangeSet",
                "cloudformation:CreateStack",
                "cloudformation:DeleteChangeSet",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeChangeSet",
                "cloudformation:DescribeStackDriftDetectionStatus",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStackResourceDrifts",
                "cloudformation:DescribeStacks",
                "cloudformation:DetectStackResourceDrift",
                "cloudformation:ExecuteChangeSet",
                "cloudformation:ListChangeSets",
                "cloudformation:ListStackResources",
                "cloudformation:UpdateStack"
            ],
            "Resource": "arn:aws:cloudformation:*:xxxxxx:stack/AWSProton-*"
        },
        {
            "Effect": "Allow",
            "NotAction": [
                "organizations:*",
                "account:*"
            ],
            "Resource": "*",
            "Condition": {
                "ForAnyValue:StringEquals": {
                    "aws:CalledVia": [
                        "cloudformation.amazonaws.com"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "organizations:DescribeOrganization",
                "account:ListRegions"
            ],
            "Resource": "*",
            "Condition": {
                "ForAnyValue:StringEquals": {
                    "aws:CalledVia": [
                        "cloudformation.amazonaws.com"
                    ]
                }
            }
        }
    ]
}
```

**Comment by Analect** [comment] 2023-04-16 16:53
With these policies against my user `analect-gitops-aws-proton-user`, I was able to move forward.

![image](https://user-images.githubusercontent.com/4063815/232327019-80111b3b-dc64-4981-b266-02f0cb2203c6.png)

However, this tutorial seems to rely on the `fargate-env` environment already being in place - something I had to manually perform in the UI.

I was then able to run the task from within the Backstage UI.

However, on the backend in AWS, the requisite AWS Proton service never got created and was stuck in an 'in progress' state forever.  On examining the CloudFormation stack, I'm assuming the failed service creation is reflected in the AWS::ECS::Service. I ended up having to delete both CloudFormation stacks (prod and dev) before it would allow me to delete the AWS Proton service. 

![image](https://user-images.githubusercontent.com/4063815/232327359-3c372722-8d36-4ee1-9626-2031cfeeec3d.png)

Maybe one of the authors can confirm that this tutorial still works. I'd be glad for any guidance.

In terms of meta-data on various resources created in AWS reported back to backstage - the AWS Proton Service card has a URL (`https://eu-west-1.console.aws.amazon.com/proton/home?region=eu-west-1#/services/detail/my-service`) under the View Source hyperlink ... but is any other meta-data captured back on Backstage ... that perhaps allows you to see all the resources created by a CloudFormation stack?  It seems to me that that would be helpful to map inter-dependent AWS resources on Backstage. Thanks

**Comment by clareliguori** [comment] 2023-04-17 17:44
Hi @Analect, I pushed some clarifications to the tutorial guide, but generally speaking, the tutorial assumes that you successfully complete the Proton getting started guide in the UI before using the Backstage plugin.  As you saw, the getting started guide includes setting up a service-linked role.  The permissions needed for setting up Proton in the UI are different from the more limited permissions needed for the Backstage plugin.  For example, the Backstage plugin does not create service-linked roles, create environments, etc, so it does not need those permissions.  For the Proton UI, you can use the [AWSProtonFullAccess policy](https://us-east-1.console.aws.amazon.com/iam/home#/policies/arn:aws:iam::aws:policy/AWSProtonFullAccess) for permissions.

https://github.com/awslabs/aws-proton-plugins-for-backstage/blob/main/docs/tutorial.md#create-prerequisite-aws-resources

**Comment by Analect** [comment] 2023-04-18 15:37
Recreated `fargate-env` which resolved VPC issue.
However, the ECS Service creation seems unstable and keeps restarting, somehow.

![ECS-service-state](https://user-images.githubusercontent.com/4063815/232827846-983e2cfe-255a-41fc-a4cd-026c7c29ad42.png)

![ECS-service-state2](https://user-images.githubusercontent.com/4063815/232828003-5b622734-e7e5-49cb-adc0-9ac4364b571a.png)

The result is that the CloudFormation process kicked off by AWS Proton never completes ... and the AWS Proton back in Backstage is perpetually stuck 'in progress'.

![image](https://user-images.githubusercontent.com/4063815/232828767-454823d8-d3ff-44ca-b402-c7fe9a4f9900.png)

I doubt this is specific to me. Have you been able to run this tutorial successfully recently?

**Comment by clareliguori** [comment] 2023-04-19 03:17
@Analect can you try the fix in 15eb66ec377ff1d2d15cf543b88c0a24f64281f1 - I confirmed on my end that I was able to complete the tutorial successfully with that fix

**Comment by Analect** [comment] 2023-04-19 09:34
Thanks @clareliguori ... that port fix got me a bit further.  However, there are issues with the pipeline build. I'm deferring to your superior knowledge here in terms of what might be going wrong.  It seems the directory referenced in the variable `$CODEBUILD_SRC_DIR` doesn't exist. See the logs at the bottom. I retried a few times to re-run that step of the pipeline, but it keeps failing here.

`/codebuild/output/tmp/script.sh: line 4: cd: /codebuild/output/src987597623/src/ecs-static-website: No such file or directory`

![aws-proton_test-aws-proton-5_pipeline-failing](https://user-images.githubusercontent.com/4063815/233030257-bf44c7e7-f659-4736-9ef8-c0b3bee75e77.png)

![image](https://user-images.githubusercontent.com/4063815/233031995-de5036c1-36c0-44d3-9f84-1e05dabd3b35.png)


![aws-proton_test-aws-proton-5_pipeline-failing-2](https://user-images.githubusercontent.com/4063815/233030481-08ac1fc9-a10c-455d-8a03-772492241c57.png)

**Comment by clareliguori** [comment] 2023-04-19 15:35
Ah I did not check whether the pipeline succeeded.  This commit should fix it: 7db1c7f6114dc0f39f5c13dd27a0d28ccd02c104

**Comment by Analect** [comment] 2023-04-19 17:08
@clareliguori  ... I finally got things working with your fixes.

I suppose I was wondering if the plugin has scope to bring back more resource meta-data from AWS than is currently the case, for Backstage to be able to give better context around these resources.

For now, there is a single entry-point to AWS from the 'VIEW SERVICE' hyperlink on the AWS Proton Service card.  There's obviously lots of moving parts that underlie that service (captured in the red rectangles) in my mockup ... 

Are the basic building-blocks in place with your plugin to be able to bring back more meta-data and ideally build out that graph component to give a better picture of the resources that go to make up this service?  Is that beyond the scope of your plugin?

![image](https://user-images.githubusercontent.com/4063815/233147907-5f0c1c38-05fe-4b8a-9f11-e38f001561a1.png)

On a related matter, can the AWS Proton plugin serve as a blueprint for accessing AWS Batch workloads? Thanks.

**Comment by clareliguori** [comment] 2023-04-19 21:18
That does seem beyond the scope of this plugin.  Proton can ensure tags like "aws:proton:service" get propagated to your CloudFormation-provisioned resources, but it doesn't "know" what resources were provisioned by CloudFormation - you need to query CloudFormation or create a Resource Group for that tag to find that out.

Since you were able to successfully use the tutorial with those fixes (yay!), I'm going to close this issue out

**Closed by clareliguori** 2023-04-19 21:18 UTC

**Comment by Analect** [comment] 2023-04-20 08:58
Thanks again for your assistance with this.
